USE [master]
GO
/****** Object:  Database [GESTAO]    Script Date: 08/02/2023 21:38:31 ******/
CREATE DATABASE [GESTAO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GESTAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\GESTAO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GESTAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\GESTAO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GESTAO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GESTAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GESTAO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GESTAO] SET ARITHABORT OFF 
GO
ALTER DATABASE [GESTAO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GESTAO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GESTAO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GESTAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GESTAO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GESTAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GESTAO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GESTAO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GESTAO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GESTAO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GESTAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GESTAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GESTAO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GESTAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GESTAO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GESTAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GESTAO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GESTAO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GESTAO] SET  MULTI_USER 
GO
ALTER DATABASE [GESTAO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GESTAO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GESTAO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GESTAO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GESTAO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GESTAO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GESTAO] SET QUERY_STORE = OFF
GO
USE [GESTAO]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 08/02/2023 21:38:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	[NOMEUSUARIO] [varchar](100) NOT NULL,
	[CPF] [varchar](15) NOT NULL,
	[EMAIL] [varchar](150) NOT NULL,
	[SENHA] [varchar](50) NOT NULL,
	[ATIVO] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [GESTAO] SET  READ_WRITE 
GO
